language: c

sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TARGET=all
  - TARGET=test

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libjack-jackd2-dev
      - portaudio19-dev
      - libfftw3-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew cask uninstall oclint || true
      brew update;
      brew install gtk+3;
      brew install portaudio;
      brew install fftw;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TARGET" == "test" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi;
    if [[ "$TARGET" == "test" ]]; then
      mkdir -p ~/.config;
    fi;

script:
  ./autogen.sh;
  ./configure;
  make "$TARGET";
